### PR TITLE
Fix crash preventing any games in 2.0.0-alpha1

### LINKED ISSUE #211: Game will not start after update 12-6-20 (v2.0.0-alpha1)
I am running Android 11 on a Pixel 2XL.  This morning I had an update for Lexica and ran it.  After updating, I am unable to start the game in the application.

The application launches and I am able to access the menus for the various settings.  If I select "New Game" the screen blanks and returns to the initial page with "New Game", "About", "Restore Game", "Preferences".  If I persist in trying to start a game I get an Android system message telling me "Lexica keeps stopping" and gives me "App Info" and "Close app" options.  Selecting "Restore Game" has no effect or sign of actually doing anything.  I can select it as many times as I want and get no Android system message.

I have restarted the phone with no change to the behavior.   

I uninstalled Lexica and reinstalled it with no change to the behavior.

### PR DESCRIPTION
**Pull request by pserwylo**
Fixes #211. See comment https://github.com/lexica/lexica/issues/211#issuecomment-742093304 for detailed description.

### CODE REVIEW

File: app/src/main/java/com/serwylo/lexica/GameActivity.java [hunk 1]
```diff
@@ -201,6 +201,7 @@ public void onResume() {
         if (game == null) {
             Toast.makeText(this, R.string.error_restoring_game, Toast.LENGTH_SHORT).show();;
             NavUtils.navigateUpFromSameTask(this);
+            return;
```
Comment (pserwylo) [inline app/src/main/java/com/serwylo/lexica/GameActivity.java:204]: Bonus fix, noticed while reading that if game is null, we will crash after this if statement unless we return.
